# Generated by Django 5.1.7 on 2025-04-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='credit_card_number',
            field=models.CharField(default='0000000000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='expiration_date',
            field=models.CharField(default='01/23', max_length=7),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_code',
            field=models.CharField(default='000', max_length=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_address',
            field=models.CharField(default='Unknown Address', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
