# Generated by Django 5.2 on 2025-04-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_city_customuser_credit_card_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(default='Unknown', max_length=100)),
                ('item_quantity', models.PositiveIntegerField()),
                ('item_description', models.CharField(default='Unknown', max_length=1000)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('item_vendor', models.CharField(max_length=1000)),
                ('item_photo', models.ImageField(height_field=100, upload_to='./images', width_field=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('delivered', 'Delivered'), ('shipped', 'Shipped'), ('ordered', 'Ordered')], default='ordered', max_length=20)),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('shipping_street_address', models.CharField(default='Unknown Address', max_length=255)),
                ('shipping_city', models.CharField(default='Unknown', max_length=100)),
                ('shipping_state', models.CharField(default='Unknown', max_length=100)),
                ('shipping_zip_code', models.CharField(default='00000', max_length=10)),
                ('order_id', models.PositiveIntegerField()),
                ('arrivaltime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='00000', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='00000', max_length=15),
        ),
    ]
