# Generated by Django 5.1.7 on 2025-04-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customshoppingcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_balance',
            field=models.IntegerField(default=10000),
        ),
    ]
