# Generated by Django 5.1.7 on 2025-05-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='item_photo',
            field=models.CharField(default='images/default.jpg', max_length=255),
        ),
    ]
