# Generated by Django 5.1.7 on 2025-05-01 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_shoppingcartitem_item_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_snapshot_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='item_photo',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='item_snapshot_id',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
