# Generated by Django 5.1.7 on 2025-05-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_orderitem_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_balance',
            field=models.FloatField(default=10000),
        ),
    ]
