# Generated by Django 5.1.7 on 2025-05-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=20),
        ),
    ]
