# Generated by Django 5.2 on 2025-04-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_item_id_item_item_id_item_item_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_items_in_cart', models.PositiveIntegerField(default=0)),
                ('user_cart_id', models.PositiveIntegerField()),
                ('cart_id', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomItem',
        ),
    ]
